// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHwzQ6cjG3fRa2rUopiYjysxkQ-ETMViM',
    appId: '1:317448817455:web:6db9856475fc513fc5afda',
    messagingSenderId: '317448817455',
    projectId: 'handcontroller-f59a1',
    authDomain: 'handcontroller-f59a1.firebaseapp.com',
    storageBucket: 'handcontroller-f59a1.appspot.com',
    measurementId: 'G-MXBPFHSDG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsL3XaErHPwhIazbpBPglAPVN4_jD5IM',
    appId: '1:317448817455:android:853ea192c4cf7ea3c5afda',
    messagingSenderId: '317448817455',
    projectId: 'handcontroller-f59a1',
    storageBucket: 'handcontroller-f59a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8BjyHtegZo8SnT4snSvE_Qz_NrvUYJEg',
    appId: '1:317448817455:ios:f839ae3f57b23a7bc5afda',
    messagingSenderId: '317448817455',
    projectId: 'handcontroller-f59a1',
    storageBucket: 'handcontroller-f59a1.appspot.com',
    iosBundleId: 'com.example.handControllerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8BjyHtegZo8SnT4snSvE_Qz_NrvUYJEg',
    appId: '1:317448817455:ios:f839ae3f57b23a7bc5afda',
    messagingSenderId: '317448817455',
    projectId: 'handcontroller-f59a1',
    storageBucket: 'handcontroller-f59a1.appspot.com',
    iosBundleId: 'com.example.handControllerApp',
  );
}
